modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/AdventureG147/Giant-Pacman-beta-0.1.1-1.16.5/issues"
license="All rights reserved"

[[mods]]
modId="giantpacman"
version="${file.jarVersion}"
displayName="Giant Pacman"
displayURL="https://www.curseforge.com/minecraft/mc-mods/giant-pacman-1-16-5"
logoFile="logo.png"
credits="AdventureG147, Blackout"
authors="AdventureG147 - Creator"
description='''This is NOT the official port to Killer Pacman. This mod was only inspired by it, and I use my own assets.'''

[[dependencies.giantpacman]]
modId="forge"
mandatory=true
versionRange="[36.2.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.giantpacman]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.giantpacman]]
modId="geckolib3"
mandatory=true
versionRange="[3.0.90,)"
ordering="NONE"
side="BOTH"

